//Copia y Pega en TradingView
// © solidlucho
//@version=1
indicator(title='Relative Strength Index/Moving Average Convergence Divergence', shorttitle='RSI/MACD')

// Configuraciones de entrada
showrsi = input(true, title='RSI VISIBLE')
showmacd = input(true, title='MACD VISIBLE')

// MACD
// Getting inputs
deltaMacd = input(100, title='MACD - Desfase')
multMacd = input(5, title='MACD - Escala')
fast_length = input(title='MACD - Fast Length', defval=12)
slow_length = input(title='MACD - Slow Length', defval=26)
src = input(title='MACD - Source', defval=close)
signal_length = input.int(title='MACD - Signal Smoothing', minval=1, maxval=50, defval=9)
sma_source = input(title='MACD - Simple MA(Oscillator)', defval=false)
sma_signal = input(title='MACD - Simple MA(Signal Line)', defval=false)

// Colores de trazado
col_grow_above = #26A69A
col_grow_below = #FFCDD2
col_fall_above = #B2DFDB
col_fall_below = #EF5350
col_macd = color.rgb(4, 247, 65)
col_signal = color.rgb(248, 7, 7)

// Cálculo MACD
fast_ma = sma_source ? ta.sma(src, fast_length) : ta.ema(src, fast_length)
slow_ma = sma_source ? ta.sma(src, slow_length) : ta.ema(src, slow_length)
macd = (fast_ma - slow_ma) / slow_ma * 1000 * multMacd
signal = sma_signal ? ta.sma(macd, signal_length) : ta.ema(macd, signal_length)
hist = macd - signal

// Trazar MACD
plot(showmacd ? hist ? hist + deltaMacd : na : na, title='MACD - Histogram', style=plot.style_columns, color=hist >= 0 ? hist[1] < hist ? col_grow_above : col_fall_above : hist[1] < hist ? col_grow_below : col_fall_below, histbase=deltaMacd)
plot(showmacd ? macd ? macd + deltaMacd : na : na, title='MACD', color=color.new(col_macd, 0))
plot(showmacd ? signal ? signal + deltaMacd : na : na, title='MACD - Signal', color=color.new(col_signal, 0))

// RSI
deltaRSI = 0
multip = 2
lengthRSI = input.int(14, minval=1, title='Longitud del RSI')
RSIMain = ta.rsi(close, lengthRSI) - 50
rsiPlot = plot(showrsi ? RSIMain * multip + deltaRSI : na, color=color.new(color.purple, 0), linewidth=2)

// Niveles de RSI
hline(showrsi ? 0 + deltaRSI : na, color=color.yellow, linestyle=hline.style_dashed, linewidth=1)
hline(showrsi ? -20 * multip + deltaRSI : na, color=color.green, linestyle=hline.style_dashed)
hline(showrsi ? 20 * multip + deltaRSI : na, color=color.red, linestyle=hline.style_dashed)

// Fondo rojo entre los niveles 30 y 70 en el RSI
level_upper = hline(20 * multip + deltaRSI, "Upper Level (70)", color=color.red)
level_lower = hline(-20 * multip + deltaRSI, "Lower Level (30)", color=color.red)
fill(level_upper, level_lower, color=color.new(color.red, 90), title="RSI Background")